#!/bin/bash
set -e

# Default file app
VERSION_FILE="VERSION"

while test $# -gt 0; do
  case "$1" in
    -o*|--output*)
      shift
      export VERSION_FILE=$1
      shift
      ;;
    *)
      break
      ;;
  esac
done

git log --merges `git describe --tags --always --abbrev=0`..HEAD --pretty=format:'%s: %b %N' > notes.txt
git config  user.email "ci@velocityapp.com"
git config  user.name "CI"
gitversion /showvariable SemVer > VERSION
cat VERSION | xargs -I % git tag -a '%' -F notes.txt
git push --tags
