#!/bin/bash
set -e

# Default file app
VERSION_FILE="VERSION"
GITVERSION="GITVERSION"

while test $# -gt 0; do
  case "$1" in
    -o*|--output*)
      shift
      export VERSION_FILE=$1
      shift
      ;;
    *)
      break
      ;;
  esac
done

gitversion > $GITVERSION
gitversion /showvariable SemVer > $VERSION_FILE
